### ISSUE TITLE
OffsetColumn RowTemplate

### ISSUE THREAD

**Issue by maximilien-noal** [Washi1337/AvaloniaHex#1]
Hello,

Thank you for making this. I've been searching for an AvaloniaUI hex control for ages !

I wish to display each row of the offset column both as a linear address and a segmented address. Perhaps with an ItemTemplate ?

Also, I have trouble setting the number of bytes to display in the data column. Moreover, how can I fix this display ?

![image](https://github.com/Washi1337/AvaloniaHex/assets/1087524/dc10ebb6-7eeb-496f-8e56-cc34f6c73b74)

Seems like data gets overwritten, visually.

This is the display of a little more of 1 MB of memory, from an IBM PC emulator.

Here is my code:

https://github.com/OpenRakis/Spice86/pull/666

Thank you again for this, this already looks way better than the old approach I was using.

**Comment by Washi1337** [comment]
> I wish to display each row of the offset column both as a linear address and a segmented address. Perhaps with an ItemTemplate ?

I am unsure what exactly you mean by this. Can you give me an example of what you're looking for?

> Also, I have trouble setting the number of bytes to display in the data column. 

There is a property called `BytesPerLine` that you can set to a non-null value to have a fixed amount of bytes per line (as opposed to it automatically adjusting to the control's width).

> Seems like data gets overwritten, visually.

This is because you're not using a monospaced font such as Consolas, Courier New or Cascadia Code. You can change the font using the `FontFamily` property.

**Comment by maximilien-noal** [comment]
> I am unsure what exactly you mean by this. Can you give me an example of what you're looking for?

For example:

linear address (segmented) | data | ascii
0000001 (0000:00001) 00 44 55 77 | <ascii text>

this would save a dedicated column.

> There is a property called BytesPerLine that you can set to a non-null value to have a fixed amount of bytes per line (as opposed to it automatically adjusting to the control's width).

I had trouble finding it. Thank you!

> This is because you're not using a monospaced font such as Consolas, Courier New or Cascadia Code. You can change the font using the FontFamily property.

Oh, right, of course. Thanks!

**Comment by Washi1337** [comment]
> this would save a dedicated column.

I wonder if this wouldn't require a dedicated custom offset column anyways. Depending on how you want to do it, segmented addressing can be different enough from simple flat addressing for it to warrant its own set of visualization logic. Furthermore, currently `IBinaryDocument` assumes flat addressing as well.

I am not a huge fan of introducing a row data template here. For performance reasons the rendering is actually not done using the standard controls of Avalonia (which a data template would rely on), but directly using `DrawingContext`s. From my (limited) testing this is especially noticeable on very large documents. However, I am still relatively new to writing custom controls in Avalonia so I could be wrong here.

Writing your own offset column should be straightforward. A column's basic needs are a way to measure its width and a way for producing the formatted `TextLine`. See [OffsetColumn.cs](https://github.com/Washi1337/AvaloniaHex/blob/main/src/AvaloniaHex/Rendering/OffsetColumn.cs). You could probably extend this easily to also display segmented addresses.

> I had trouble finding it. Thank you!

I don't blame you. This project currently has a severe lack of documentation and maturity (there is a reason it is versioned 0.1 and not 1.0) . Many properties in `HexView` such as `BytesPerLine` should probably be also exposed in `HexEditor` such that it can be more easily defined and bound to in the AXAML for better MVVM support. The best documentation right now is the example project's [MainWindow.axaml](https://github.com/Washi1337/AvaloniaHex/blob/main/examples/AvaloniaHex.Demo/MainWindow.axaml.cs)

**Comment by maximilien-noal** [comment]
Thank you, I made my own AddressColumn, and fixed my issue.

I think that the design where I can add my won custom column is really great.

Also the performance is really good, I think your approach to it is the right one.
