### ISSUE TITLE
Removing/inserting bytes to a hex editor

### ISSUE THREAD

**Issue by kb-1000** [Washi1337/AvaloniaHex#10]
CanRemove and RemoveBytes exist, but appear to be unused.

**Comment by kb-1000** [comment]
Inserting also seems to behave quite weirdly in general - so currently more or less everything but viewing and editing existing bytes appears to be broken. Unfortunately there's also no builtin resizable `IBinaryDocument`, though currently there wouldn't be much of a point anyways. I created my own using a `List<byte>`, could PR it if this gets fixed.
This screenshot shows some (but not all) of the weirdness, created by repeatedly typing A in varying locations:
![image](https://github.com/user-attachments/assets/d29d5f40-4013-4a8f-a08b-1087b081ed98)
It only really lets you edit one of the two half-bytes in insert mode.

**Comment by Washi1337** [comment]
This is correct. Currently the control only fully supports viewing and editing existing bytes. This is also one of the reasons there is no dynamically resizable binary document implementation yet. The interface methods are currently there as a WIP / future work.

Ideally, for a dynamically resizable document we should not use `List<byte>`, as this would result in insert and remove becoming O(n) operations, which is really bad for large documents of several 100s of megabytes to gigabytes.

**Comment by Washi1337** [comment]
Status update: Initial implementation of dynamic sized documents can be found in #11.

**Comment by Washi1337** [comment]
Implemented in #11, will be present in the next nuget version bump.
