### ISSUE TITLE
IBinaryDocument for region of Virtual Memory

### ISSUE THREAD

**Issue by denys-volodarskyi** [Washi1337/AvaloniaHex#6]
Hello, thanks for the great project.

What's the proper way to implement IBinaryDocument for regions of virtual memory?

For example if I create range ``0x400000 .. 0x401000``, first ReadBytes is called with offset 0, not 0x400000.

```csharp
public class VirtualMemorySingleRangeDocument(IMemoryCursor cursor, VirtualMemoryLocation location, ulong length) : IBinaryDocument
{
    public ulong Length { get; } = length;
    
    public IReadOnlyBitRangeUnion ValidRanges { get; } = new BitRangeUnion([new BitRange(location.Address, location.Address + length)]).AsReadOnly();

    public void ReadBytes(ulong offset, Span<byte> buffer)
    {
        if (!cursor.TrySeek(offset))
            throw new($"Failed to seek address 0x{offset:X}");

        if (cursor.Read(buffer) is var cnt && cnt != buffer.Length)
            throw new($"Hex document read {cnt} of {buffer.Length} bytes");
    }
}
```

So it seems expects 0 based ranges, i.e.

```csharp
public IReadOnlyBitRangeUnion ValidRanges { get; } = new BitRangeUnion([new BitRange(0, length)]).AsReadOnly();
```

This works. Is it by-design and I should use latter?

Also it shows zero-based offsets (I'd like to show VA or RVA instead of offset):

![image](https://github.com/user-attachments/assets/e87e3a36-f74e-4cbd-a027-a46463219bcb)

**Comment by Washi1337** [comment]
Currently, the implementation just calls `ReadBytes` regardless of what is stored in `ValidRanges`. `ValidRanges` is currently more or less a visual layer on top of the raw data, and `ReadBytes` is assumed to not throw but simply skip (or leave zero) the bytes that are invalid. I intend to have it only call `ReadBytes` on the actual valid disjoint ranges (or wait for someone to PR this :upside_down_face:), it just hasn't happened yet.

See also [SegmentedDocument.cs](https://github.com/Washi1337/AvaloniaHex/blob/dd7de467e3aba32030b32c3746219dd9b74fa434/examples/AvaloniaHex.Demo/SegmentedDocument.cs) in the example project on a simple implementation that uses `ValidRanges` (can be activated in the demo app using File > Open Example > Segmented Document).
